repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v0.9.4
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: ^\.activate\.sh$
          - id: check-yaml
          - id: debug-statements
          - id: name-tests-test
          - id: requirements-txt-fixer
          - id: check-added-large-files
            exclude: ^(\.activate\.sh)$
          - id: check-byte-order-marker
          - id: fix-encoding-pragma
            args: [--remove]
          - id: flake8
            args: [
                '--ignore=E121,E123,E126,E133,E203,E226,E231,E241,E242,E501,E704,W503,W504,W505,W605'
            ]
    - repo: https://github.com/asottile/reorder_python_imports
      rev: v3.8.2
      hooks:
          - id: reorder-python-imports
            args: [
                --remove-import, from __future__ import absolute_import,
                --remove-import, from __future__ import print_function,
                --remove-import, from __future__ import unicode_literals
            ]
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.37.3
      hooks:
          - id: pyupgrade
            args: [--py3-plus]
    - repo: http://github.com/psf/black
      rev: 22.8.0
      hooks:
          - id: black
            language_version: python3.8
            args:
                - --target-version
                - py38
